# Generated by Django 5.2.5 on 2025-08-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('property_type', models.CharField(blank=True, max_length=50)),
                ('bedroom_type', models.CharField(blank=True, max_length=50)),
                ('requirements', models.TextField(blank=True)),
                ('page_url', models.URLField(blank=True)),
                ('referrer', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('villa_type', models.CharField(choices=[('townhouse', 'Townhouse'), ('villa', 'Villa')], max_length=20)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('area_sqft', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='villas/')),
                ('floor_plan', models.FileField(blank=True, null=True, upload_to='floorplans/')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
