# Generated by Django 5.2.5 on 2025-08-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('villa_type', models.CharField(choices=[('townhouse', 'Townhouse'), ('villa', 'Villa')], max_length=20)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('area_sqft', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='villas/')),
                ('floor_plan', models.FileField(blank=True, null=True, upload_to='floorplans/')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
